# 端口配置
server:
  port: 8080
  servlet:
    session:
      timeout: 21600

spring:
  application:
    name: blog-web

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/blog-v2.0?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8 # %2B
    url: jdbc:mysql://119.91.95.127:3306/blogv2?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8 # %2B
    #        url: jdbc:mysql://localhost:3306/blog
    username: root
    password: ShiFan53110
    #    password: admin
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认10秒，即10000
      connection-timeout: 10000
      connection-test-query: SELECT 1

  redis:
    host: 119.91.95.127
    #    host: localhost
    port: 6379
    password: redis-123456

  devtools:
    restart:
      enabled: false

  # 上传图片大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size:  100MB

  rabbitmq:
    host: 119.91.95.127
    port: 5672
    username: admin
    password: admin-rabbitmq
    #    virtual-host: my_vhost
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3 #最大重试次数
          initial-interval: 3000 #重试间隔时间（单位毫秒）
  mail:
    host: smtp.qq.com
    username: 584273128@qq.com
    password: aihkluhepmnwbfdj
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
      smtp:
      auth: true
      socketFactory:
      class: javax.net.ssl.SSLSocketFactory

# 上传模式 可选 oss或local  （http://和最后的/一定不能去！！！）
upload:
  mode: oss
  local:
    # nginx映射本地文件路径，无域名则为 ip:83
    url: http://你的文件上传子域名/
    # 本地文件存储路径
    path: /usr/local/upload/
  oss:
    url: http://finn-blog.oss-cn-shanghai.aliyuncs.com/
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI5t73cfK9GRWinoxSyhBk
    accessKeySecret: 1rvSy6sl7whWONyoz1OPkcE29c0cpc
    bucketName: finn-blog

mybatis-plus:
  #The classpath*:conf/appContext.xml simply means that allx appContext.xml files under conf folders in all your jars on the classpath will be picked up and joined into one big application context.
  #In contrast, classpath:conf/appContext.xml will load only one such file... the first one found on your classpath.
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

enable:
  swagger2: true

website:
  url: http://finn-web.top