# 端口配置
server:
  port: 8080
  servlet:
    session:
      timeout: 21600

spring:
  application:
    name: blog-web

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog-v2.0?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8 # %2B
#    url: jdbc:mysql://119.91.95.127:3306/blog?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8 # %2B
    #    url: jdbc:mysql://localhost:3306/blog
    username: root
#    password: ShiFan53110
    password: admin
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
#    host: 119.91.95.127
    host: localhost
    port: 6379
#    password: redis-123456

  devtools:
    restart:
      enabled: false

mybatis-plus:
  #The classpath*:conf/appContext.xml simply means that allx appContext.xml files under conf folders in all your jars on the classpath will be picked up and joined into one big application context.
  #In contrast, classpath:conf/appContext.xml will load only one such file... the first one found on your classpath.
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

enable:
  swagger2: true

